/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { TextField, Avatar, Switch, FormControlLabel } from '@mui/material';
import Avatar1Image from 'src/assets/images/test1_Avatar.png';
import { styled } from '@mui/material/styles';

 
const Test11 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `446px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const TextFieldStandard = styled(TextField)({  
  width: `220px`,  
  position: `absolute`,  
  left: `24px`,  
  top: `24px`,  
});
  
const Avatar1 = styled(Avatar)({  
  position: `absolute`,  
  left: `114px`,  
  top: `165px`,  
  width: `40px`,  
  height: `40px`,  
});
  
const FormControlLabel1 = styled(FormControlLabel)({  
  position: `absolute`,  
  left: `270px`,  
  top: `210px`,  
  margin: `0px`,  
});
 
function Test1(props) {
  return (
    <Test11  className={props.className}   >
      <TextFieldStandard variant="standard" size="medium"  label={`Label`}    />
      <Avatar1 variant="square" src={Avatar1Image} alt={"Avatar"}   />
      <FormControlLabel1 control={<Switch defaultChecked={true} color="primary" size="medium" />} label={"Label"} />
    </Test11>
  );
}

export default Test1;
